name: Atlantis Images Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - LICENSE
      - README.md
  schedule:
    - cron: 0 0 * * 0

jobs:
  atlantis:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: full360/atlantis
          tag-sha: true
          tag-latest: true
          tag-schedule: {{date 'YYYYMMDD'}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Atlantis Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}

